#include <stdio.h>
#include<conio.h>
#include<dos.h>
int main()
{
	int a=1;
	do
	{
 clrscr();
    printf("         * *         * *        \n");
sleep(1);
   printf("       *     *     *     *        \n ");
 sleep(1);
    printf("    *         * *        *     \n    ");
sleep(1);
    printf(" *          *          *    \n   ");
sleep(1);
    printf("  *                     *    \n  ");
sleep(1);
    printf("   *                     *    \n    ");
sleep(1);
    printf("  *                    *   \n ");
sleep(1);
    printf("      *                  *   \n  ");
sleep(1);
    printf("      *                *    \n ");
sleep(1);
    printf("         *             *    \n ");
sleep(1);
    printf("          *           *    \n ");
 sleep(1);
    printf("            *       *    \n");
sleep(1);
    printf("               *   * \n  ");
sleep(1);
    printf("               *   \n ");
sleep(1);
getch();
	}while(a==1);
}

