#include<stdio.h> 
#include <conio.h>
#include<stdlib.h>
#include<string.h>
#include<time.h>
#include<dos.h>
int main()
{
	clrscr();
	printf("\t\t\tren gui ying");
	sleep(1);
	clrscr();
	gotoxy(15,8);
	printf("i");
	sleep(1);
	clrscr();
	gotoxy(25,15);
	printf("love");
	sleep(1);
	clrscr();
	gotoxy(35,8);
	printf("you");
	sleep(1);
	clrscr();
	gotoxy(10,4);
	printf("i love you");
	sleep(1);
	//clrscr();
	gotoxy(15,8);
	printf("never give up");
	sleep(1);
	//clrscr();
	gotoxy(20,12);
	printf("now or ever");
	gotoxy(30,15);
	printf("_____________for my love");
getch();
return 0;
}

