#include <stdio.h>
#include <conio.h>
#include<graphics.h>
#include<dos.h>
void main()
{
clrscr();
textbackground(0);
textcolor(128);
clrscr();
window(5,1,10,3);
textbackground(4);
clrscr();
window(5,3,10,6);
textbackground(5);
clrscr();
window(5,6,10,9);
textbackground(14);
clrscr();
window(5,9,10,12);
textbackground(10);
clrscr();
window(5,12,10,15);
textbackground(10);
clrscr();
window(5,15,10,18);
textbackground(11);
clrscr();
window(5,18,10,21);
textbackground(9);
clrscr();
window(5,21,10,24);
textbackground(1);
clrscr();
getch();
}
